//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamEdrian.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ExamEdrian.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ParkCode {
            get {
                return ResourceManager.GetString("ParkCode", resourceCulture);
            }
        }
        
        public static string ParkCodePlaceholder {
            get {
                return ResourceManager.GetString("ParkCodePlaceholder", resourceCulture);
            }
        }
        
        public static string ParkCodeErrorMessage {
            get {
                return ResourceManager.GetString("ParkCodeErrorMessage", resourceCulture);
            }
        }
        
        public static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        public static string ArrivalDatePlaceholder {
            get {
                return ResourceManager.GetString("ArrivalDatePlaceholder", resourceCulture);
            }
        }
        
        public static string SearchPage {
            get {
                return ResourceManager.GetString("SearchPage", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string GuestName {
            get {
                return ResourceManager.GetString("GuestName", resourceCulture);
            }
        }
        
        public static string Arrived {
            get {
                return ResourceManager.GetString("Arrived", resourceCulture);
            }
        }
        
        public static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        public static string SavingFailed {
            get {
                return ResourceManager.GetString("SavingFailed", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SaveSuccessfully {
            get {
                return ResourceManager.GetString("SaveSuccessfully", resourceCulture);
            }
        }
    }
}
